on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-coverage

permissions:
  contents: read
  checks: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::stringr
            any::readr
            any::dplyr
            any::digest
            any::glue
            any::testthat
            any::devtools

      - name: Run tests
        run: Rscript -e 'devtools::test()'

      - name: Generate and save coverage report
        run: Rscript -e 'covr::package_coverage(path = ".", type = "lcov", output_file = "coverage.lcov")'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN || '' }}

      - name: Debug coverage generation
        run: Rscript -e 'print(covr::package_coverage())'
