on:
  push:
    branches: main
  pull_request:
    branches: main

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::stringr
            any::readr
            any::dplyr
            any::digest
            any::glue
            any::testthat
            any::devtools
          needs: coverage

      - name: Test coverage
        run: Rscript -e 'covr::codecov()'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
